language: python

python:
    - "2.7"
#    - "2.6"
#    - "pypy"
#    - "3.3"

install:
  - sudo apt-get install libevent-dev
  - sudo apt-get install graphviz
  - python setup.py install
  - python setup.py test
  - pip install -r test-requirements.txt

script:
  - pep8 --ignore=E501 RCubic/*.py
  - pylint --rcfile=pylintrc RCubic/*.py
  - nosetests tests/*.py
