language: python

python:
    - "2.7"
    - "2.6"
# gevent does not build in python 3.3 because of print_function
#    - "3.3"
# gevent does not build in pypy because of missing fields
#    - "pypy"

install:
  - sudo apt-get install libevent-dev graphviz
  - pip install --use-mirrors -r requirements.txt
  - pip install --use-mirrors -r test-requirements.txt
  - python setup.py install
  - python setup.py test

script:
  - pep8 --ignore=E501 RCubic/*.py
  - pylint --rcfile=pylintrc RCubic/*.py
  - nosetests tests/*.py
